### ISSUE TITLE
Fine tune 120b at 8 H100s getting cuda OOM error

### ISSUE THREAD

**Issue by imxj** [huggingface/gpt-oss-recipes#23]
I am using the sft.py + Lora.yaml to fine tune gpt oss 120b. The OpenAI blog (https://cookbook.openai.com/articles/gpt-oss/fine-tune-transfomers) mentioned it is doable on single H100, but I kept getting OOM. Any one successfully fine tuned it on H100?

**Comment by rjarun8235** [comment]
@imxj  At what point are you getting the OOM error? I tried on an H100 GPU with a custom dataset of 100 samples, and it worked just fine. 

_This part of the implementation is very crucial:_

```
import torch
from transformers import AutoModelForCausalLM, Mxfp4Config

quantization_config = Mxfp4Config(dequantize=True)
model_kwargs = dict(
    attn_implementation="eager",
    torch_dtype=torch.bfloat16,
    quantization_config=quantization_config,
    use_cache=False,
    device_map="auto",
)

```

Also, you can try tweaking.
```
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    max_length=2048,
```

observing GPU utilization can give more visibility via GPUStat,htop,nvtop, etc

**Comment by rjarun8235** [comment]
> [@imxj](https://github.com/imxj) At what point are you getting the OOM error? I tried on an H100 GPU with a custom dataset of 100 samples, and it worked just fine.
> 
> _This part of the implementation is very crucial:_
> 
> ```
> import torch
> from transformers import AutoModelForCausalLM, Mxfp4Config
> 
> quantization_config = Mxfp4Config(dequantize=True)
> model_kwargs = dict(
>     attn_implementation="eager",
>     torch_dtype=torch.bfloat16,
>     quantization_config=quantization_config,
>     use_cache=False,
>     device_map="auto",
> )
> ```
> 
> Also, you can try tweaking.
> 
> ```
>     per_device_train_batch_size=4,
>     gradient_accumulation_steps=4,
>     max_length=2048,
> ```
> 
> observing GPU utilization can give more visibility via GPUStat,htop,nvtop, etc

And the example "https://cookbook.openai.com/articles/gpt-oss/fine-tune-transfomers" mentioned here is on a 20b - 

Maybe the example you are looking for here: https://github.com/openai/gpt-oss, where triton kernel is used for the optimization of the MoE attention

**Comment by exist-unique** [comment]
Also seeing CUDA OOM when training 120b on 8 x H100

**Comment by imxj** [comment]
@rjarun8235 I was using this command to fine tune 120b model and didn't change the sft.py code and configs.

accelerate launch \
    --config_file configs/zero3.yaml \
    sft.py \
    --config configs/sft_lora.yaml \
    --model_name_or_path openai/gpt-oss-120b \
    --packing true packing_strategy wrapped \
    --run_name 120b-full-eager \
    --attn_implementation kernels-community/vllm-flash-attn3

The OOM happens at the load model step: 
 model = AutoModelForCausalLM.from_pretrained(
        model_args.model_name_or_path, **model_kwargs
    )

The progress bar went to 67%, and then got OOM error.

One more information: I am using 80GB H100

**Comment by nandhakumarsuriya** [comment]
@imxj Can you try lowering the max_length param in defining SFTConfig, This worked for me.

```
from trl import SFTConfig

training_args = SFTConfig(
    learning_rate=2e-4,
    gradient_checkpointing=True,
    num_train_epochs=1,
    logging_steps=1,
    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    max_length=512,
    warmup_ratio=0.03,
    lr_scheduler_type="cosine_with_min_lr",
    lr_scheduler_kwargs={"min_lr_rate": 0.1},
    output_dir="gpt-oss-20b-qad",
    report_to="trackio",
    push_to_hub=True,
)

```

**Comment by imxj** [comment]
@nandhakumarsuriya No, a length of 512 didn’t work either. If possible, could you share your full script? Many of us are interested in a successful 120B fine-tuning.

**Comment by nandhakumarsuriya** [comment]
@imxj I have not fine-tuned 120b model on H100, but i have fine-tuned 20b model on H100 loaded with bfp16 (for fine-tuning) and it took ~43 GB out of 80GB VRam for model loading.

This workbook is for fine-tuning 20b model - "https://cookbook.openai.com/articles/gpt-oss/fine-tune-transfomers"
For fine-tuning 120b model, you have dequantize it and load in bfloat16, So the model will be loaded in it's full size (not in it's quantized size).

`quantization_config = Mxfp4Config(dequantize=True)`


Model size   | Precision Format | Calculation          | Estimated VRAM Required
------------ | -----------------| ----------------  | ---------------------------
120b               |      BF16 / FP16    | 120B * 2 bytes     |   ~240 GB
20b             |      BF16 / FP16    | 20B * 2 bytes       |   ~40 GB
120b               |      MxFP4           |  120B * 0.5 bytes  |   ~60 GB (in addition with tokenizers and stuffs you see 66.62 GB in huggingface)
20b             |      MxFP4           |  20B * 0.5 bytes    |   ~10 GB (in addition with tokenizers and stuffs you see 13.7 GB in huggingface)


Based on this you need to configure you GPUs accordingly

**Comment by ashwaniyadav09** [comment]
@imxj did the finetuning of gpt-oss-120b work for you? Can you please share the setup which worked?
